### ISSUE TITLE
Have to explicitly include `Sneakers::Worker` in workers defined in a Rails environment

### ISSUE THREAD

**Issue by gabrieljoelc** [giftcardzen/la_gear#1]
See https://github.com/gabrieljoelc/la_gear/blob/master/lib/la_gear/worker.rb#L6.

**Comment by crazydog115** [comment]
I removed the
```ruby
  include Sneakers::Worker unless LaGear::Worker.sidekiq_proc?
  include Sidekiq::Worker
```
lines in the workers in the [main app update-lagear](https://github.com/giftcardzen/main-app/tree/feature/update-lagear) branch, and the web server and sneakers/sidekiq/worker processes started just fine.

Does that mean this is fixed? Or is the issue caused when a worker is run?

**Comment by crazydog115** [comment]
What are the symptoms of this issue?

**Comment by gabrieljoelc** [comment]
I just thought things didn't work so if all is working, then I think all is fixed. I guess you push to staging to test a prod like environment.

**Comment by crazydog115** [comment]
Pushing to staging right now to test w/ staging VP app

**Comment by crazydog115** [comment]
Message was published and received just fine.
