### ISSUE TITLE
Update CI to test more versions of Ruby and ActiveSupport

### ISSUE THREAD

**Issue by gabrieljoelc** [giftcardzen/la_gear#89]
Test
- 2.1.9
- 2.2.2
- 2.4.1

**Comment by gabrieljoelc** [comment]
2.1.9 is failing with:
```
Sidekiq 5.0.3 does not support Ruby versions below 2.2.2
```
I may need to adjust the sidekiq version in the gemspec

**Comment by jd-gray** [comment]
Hmm should also fail with this as well: https://github.com/giftcardzen/deploy-script/issues/170#issuecomment-327298594

**Comment by gabrieljoelc** [comment]
Here's an example of the three pipelines: https://app.codeship.com/projects/82628/builds/28202848
